### ISSUE TITLE
Due Date:

### ISSUE THREAD

**Issue by Kahan7777** [takos22/timathon-for-students#1]
### A suggestion : Instead of just storing _dd-mm-yyyy_ store _seconds-minutes-hours-day-months-year_
cause then it also allows you to schedule your day. Otherwise, it's pretty wholesome!

**Comment by takos22** [comment]
Thanks you for the feedback but I do store a full datetime object as you can see it in [the Homework model](https://github.com/takos22/timathon-for-students/blob/master/api/models/homework.py#L11), and the formatting is `YYYY-MM-DD hh:mm` as you can see it in [the homework template](https://github.com/takos22/timathon-for-students/blob/master/website/templates/homework.html#L75). So you should be able to set the hour and minutes, and seconds aren't important for a homework in my opinion.
